---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-conf
  labels:
    name: prom-conf
data:
  prometheus.rules: |-
    groups:
    - name: keda demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'go-prom-job'
        kubernetes_sd_configs:
        - role: service
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_label_run]
          regex: keda-demo-app-service
          action: keep
      - job_name: 'go-prom-pod-cycle'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_phase]
          regex: go-prom-pod-cycle
          action: keep
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
      - job_name: 'keda-metrics'
        static_configs:
          - targets: ['keda-operator-metrics-apiserver.keda.svc.cluster.local:9022']
      - job_name: 'keda-operator'
        static_configs:
          - targets: ['keda-operator.keda.svc.cluster.local:8080']
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus-service.keda.svc.cluster.local:8080', 'prometheus.keda-demo.svc.cluster.local:8081']
            labels:
              group: 'prometheus'